### ISSUE TITLE
在安卓手机上有两个问题

### ISSUE THREAD

**Issue by sml2h3** [apicloudcom/UIChatBox#2]
第一、在子Frame中弹出键盘，会把整个父Win向上推移，在安卓平台下，iphone没问题（我的安卓测试机是红米NOTE3）
第二、安卓键盘弹出的时候，似乎将输入框那部分工具栏下面遮挡了一部分，不好看

**Comment by youdelu** [comment]
运行不了  直接报错
......
at com.uzmap.pkg.uzmodules.uzUIChatBox.UzUIChatBox.initSendBtnBg(UzUIChatBox.java:914)
at com.uzmap.pkg.uzmodules.uzUIChatBox.UzUIChatBox.initSendBtnStyles(UzUIChatBox.java:1452)
at com.uzmap.pkg.uzcore.uzmodule.UZModule.makeRealPath(UZModule.java:211)
at com.uzmap.pkg.uzmodules.uzUIChatBox.UzUIChatBox.getViewBackground(UzUIChatBox.java:1489)
......

**Comment by sunzhengcuan** [comment]
新版本已修复此问题
